# Generated by Django 4.2.5 on 2023-09-20 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='lessons',
            field=models.ManyToManyField(related_name='products', to='education_app.lesson'),
        ),
        migrations.AlterField(
            model_name='lessonprogress',
            name='products',
            field=models.ManyToManyField(related_name='lesson_progresses', to='education_app.product'),
        ),
    ]
